name: Build Android APK

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout
      - name: Checkout repository
        uses: actions/checkout@v4

      # Node
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      # Dependencies
      - name: Install dependencies
        run: npm install

      # EAS CLI
      - name: Install EAS CLI
        run: npm install -g eas-cli

      # Expo Login
      - name: Expo Login
        run: eas whoami
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}

      # Build APK
      - name: Build APK
        id: build
        run: |
          eas build \
            --platform android \
            --profile preview \
            --non-interactive \
            --wait \
            --json > build.json
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}

      # Extract APK URL
      - name: Extract APK URL
        id: extract
        run: |
          sudo apt-get update
          sudo apt-get install -y jq

          APK_URL=$(cat build.json | jq -r '.[0].artifacts.buildUrl')

          echo "APK_URL=$APK_URL" >> $GITHUB_ENV

          echo "APK URL:"
          echo $APK_URL

      # Download APK
      - name: Download APK
        run: |
          curl -L "$APK_URL" -o app-release.apk

      # Upload Artifact
      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: app-release.apk

      # Create Release
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ github.run_number }}
          name: Release v${{ github.run_number }}
          files: app-release.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}